/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/archive': RouteRecordInfo<'/archive', '/archive', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/bugs': RouteRecordInfo<'/bugs', '/bugs', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/nav': RouteRecordInfo<'/nav', '/nav', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/module': RouteRecordInfo<'/posts/module', '/posts/module', Record<never, never>, Record<never, never>>,
    '/posts/package-manager': RouteRecordInfo<'/posts/package-manager', '/posts/package-manager', Record<never, never>, Record<never, never>>,
    '/posts/workflow/code-style-standard': RouteRecordInfo<'/posts/workflow/code-style-standard', '/posts/workflow/code-style-standard', Record<never, never>, Record<never, never>>,
    '/posts/workflow/code-style-standard-new': RouteRecordInfo<'/posts/workflow/code-style-standard-new', '/posts/workflow/code-style-standard-new', Record<never, never>, Record<never, never>>,
    '/posts/workflow/programming-standard': RouteRecordInfo<'/posts/workflow/programming-standard', '/posts/workflow/programming-standard', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/todo': RouteRecordInfo<'/todo', '/todo', Record<never, never>, Record<never, never>>,
    '/workflow': RouteRecordInfo<'/workflow', '/workflow', Record<never, never>, Record<never, never>>,
  }
}
