/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/archive': RouteRecordInfo<'/archive', '/archive', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/bugs': RouteRecordInfo<'/bugs', '/bugs', Record<never, never>, Record<never, never>>,
    '/nav': RouteRecordInfo<'/nav', '/nav', Record<never, never>, Record<never, never>>,
    '/others': RouteRecordInfo<'/others', '/others', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/custom-block-and-code': RouteRecordInfo<'/posts/custom-block-and-code', '/posts/custom-block-and-code', Record<never, never>, Record<never, never>>,
    '/posts/garbage-collection': RouteRecordInfo<'/posts/garbage-collection', '/posts/garbage-collection', Record<never, never>, Record<never, never>>,
    '/posts/module': RouteRecordInfo<'/posts/module', '/posts/module', Record<never, never>, Record<never, never>>,
    '/posts/package-manager': RouteRecordInfo<'/posts/package-manager', '/posts/package-manager', Record<never, never>, Record<never, never>>,
    '/posts/sharp-install-failed': RouteRecordInfo<'/posts/sharp-install-failed', '/posts/sharp-install-failed', Record<never, never>, Record<never, never>>,
    '/posts/vue-diving-component': RouteRecordInfo<'/posts/vue-diving-component', '/posts/vue-diving-component', Record<never, never>, Record<never, never>>,
    '/posts/vun-base': RouteRecordInfo<'/posts/vun-base', '/posts/vun-base', Record<never, never>, Record<never, never>>,
    '/posts/workflow/code-style-standard': RouteRecordInfo<'/posts/workflow/code-style-standard', '/posts/workflow/code-style-standard', Record<never, never>, Record<never, never>>,
    '/posts/workflow/code-style-standard-new': RouteRecordInfo<'/posts/workflow/code-style-standard-new', '/posts/workflow/code-style-standard-new', Record<never, never>, Record<never, never>>,
    '/posts/workflow/git': RouteRecordInfo<'/posts/workflow/git', '/posts/workflow/git', Record<never, never>, Record<never, never>>,
    '/posts/workflow/npm': RouteRecordInfo<'/posts/workflow/npm', '/posts/workflow/npm', Record<never, never>, Record<never, never>>,
    '/posts/workflow/programming-standard': RouteRecordInfo<'/posts/workflow/programming-standard', '/posts/workflow/programming-standard', Record<never, never>, Record<never, never>>,
    '/todo': RouteRecordInfo<'/todo', '/todo', Record<never, never>, Record<never, never>>,
    '/workflow': RouteRecordInfo<'/workflow', '/workflow', Record<never, never>, Record<never, never>>,
  }
}
